### ISSUE TITLE
afSlingshot object not saved

### ISSUE THREAD

**Issue by abhaytalreja** [ElevateDev/meteor-autoform-slingshot#1]
Hi There,

Thank you so much for the package, it works great! However, when i am using quickforms, i am not able to save the data when i add the images. I also checked, images are getting stored in my S3 drive.

All i am looking 

```
MyObj.schema = new SimpleSchema({
someField{

},
.... more fields,
files: {
    type: [afSlingshot.fileSchema],
    optional: true,
    editableBy: ["admin"],
    autoform: {
      type: 'slingshot', // (required)
      multi: true,
      ui: {
        showDownload: true
      },
      slingshot: {
        directives: [
          {
            name: "thumbnails",
            onBeforeUpload: function(file, callback) {
              var settings = {
                width: 212,
                height: 312,
                cropSquare: false
              };
              Resizer.resize( file, settings, callback );
            }
          },{
            name: 'files'
          }
        ],
      }
    }
  }
});
```

Do i need to write any custom code? I do have my server code also working.. How can i make sure that the files get saved to the `MyObj` 

I am using telescope to add the image to the Posts object.

Any help will be great!

Regards,
Abhay

**Comment by jimmiebtlr** [comment]
Is anything getting logged to console?  Would you mind enabling AutoForm and SimpleSchema debugging to see if anything is showing up there.

Should be something like 

```
AutoForm.debug = true;    
SimpleSchema.debug = true;
```

**Comment by jimmiebtlr** [comment]
Just to double check, you are attaching that schema to a mongo collection?

**Comment by abhaytalreja** [comment]
Sorry, it actually worked.. I was playing around with an already existing record and the new field i added to the auto-form. When i tried it with a new record creation... all the CRUD operations worked. 

Thanks for following up! works well...

Just an FYI.. With bootstrap 4, the wells, thumbnails, panels will be deprecated... it will make use of cards, it will be great if you can update it.
